import styled, {keyframes} from "styled-components";


//animation define
/* ----------------------------------------------
 * Generated by Animista on 2022-8-15 13:11:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tilt-in-top-2
 * ----------------------------------------
 */
const fadein = keyframes`
    0% {
        transform: translateY(-50px);
        opacity: 0;
    }
    100% {
        transform: translateY(0);
        opacity: 1;
    }
`;

const fadeout = keyframes`
    0% {
        transform: translateY(0);
        opacity: 1;
    }
    100% {
        transform: translateY(-50px);
        opacity: 0;
    } 
`;


//Media
export const MediaDiv = styled.div`
    margin: 0px auto;
`;

//main
export const Main = styled.div`
    width: 700px;
    margin: 0 auto;
    margin-bottom: 50px;
`;

export const ListMain = styled.div`
    width: 1024px;
    margin: 0 auto;
    display: flex;
    margin-bottom: 20px;
`;


//Header
export const Header = styled.div`
    height: auto;
    display: flex;
    flex-direction: column;
`;

export const HeaderDiv = styled.div`
    height: auto;
    display: flex;
    flex-direction: column;
`;

//Header-Logo, Search, Sign
export const TopDiv = styled.div`
    margin-Top: 25px;
    margin-right: 50px;
    margin-left: 50px;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;

    img {
        cursor: pointer;
    }
`;

export const SearchSign = styled.div`
    width: 720px;
    color: #767676;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    justify-content: flex-end;
    align-items: center;
`;

export const Search = styled.div`
    width: 380px;
    height: 50px;
    border: 1px solid #439F68;
    background-color: white;
    border-radius: 10px;
    display: flex;
    flex-direction: row;
    justify-content: space-around;
    align-items: center;
    padding-left: 10px;

    input {
        width: 300px;
        border: none;
        font-size: 16px;
        font-weight: regular;
    }

    input:focus {
        outline: none;
    }
`;

export const Sign = styled.div`
    width: 125px;
    font-size: 16px;
    font-weight: regular;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    padding-left:50px;
    padding-right:10px;

    p {
        cursor: pointer;
        &:hover {
            color: #000000;
            transition: .3s cubic-bezier(0.43,-0.02, 0.49, 0.95) !important;
        }
    }

`;

//Header-Navbar
export const NavbarDiv = styled.div`
    margin-right: 50px;
    margin-left: 50px;
`;

export const NavTitle = styled.div`
    width: 250px;
    height: 50px;
    display: flex;
    flex-direction: row;
    justify-content: space-around;

    a {
        color: #767676;
    }
    a:link {
        text-decoration: none;
    }
    a:hover {
        transition: .3s cubic-bezier(0.43,-0.02, 0.49, 0.95) !important;
        color: #000000;
        text-decoration: none;
    }

    .active{
        text-decoration: none;
        color: #000000;
    }
`;

export const NavBox = styled.div`
    width: 250px;
    margin:0px;
    padding: 0px;
    position: absolute;
    top: 262.5px;
    z-index: 5;

    .box {
        width: 125px;
        height: 7px;
        background-color: #5CBE81;
        margin: 0px;
        padding: 0px;
        transition: left 0.25s ease-in-out 0s;
    }
`;

export const Navbar = styled.div`
    display: column;
    hr {
        background-color: #BFBFBF;
        opacity: 50%;
        height: 1px;
        margin: 0;
        padding: 0;
        border: none;
    }
`;

//Header-MenuInfo
export const MenuInfo = styled.div`
    width: 1300px;
    margin: 50px 50px 15px 50px;
    display: flex;
    flex-direction: column;
    
`;
export const InfoBig = styled.span`
    font-size: 32px;
    color: #000000;
    font-weight: 900;
    span {
        color: #439F68;
    }
`;
export const InfoSmall = styled.span`
    font-size: 16px;
    color: #767676;
    padding-left: 4px;
    font-weight: 400;
`;


//ListSearch
export const PostListDiv = styled.div`
    width: 870px;
    margin-left: 30px;
    padding: 20px 0px 20px 20px;

    hr {
        background-color: #BFBFBF;
        height: 1px;
        border: none;
        opacity: 50%;
    }
`;
export const PostSearchDiv = styled.div`
    display: flex;
    width: 880px;
    align-items: center;
    justify-content: center;
`;
export const PostSearch = styled.div`
    width: 525px;
    height: 50px;
    border: 1px solid #439F68;
    background-color: #F8F8F8;
    border-radius: 25px;
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
    padding: 0 20px;

    input {
        width: 500px;
        border: none;
        font-size: 16px;
        font-weight: regular;
        background-color: #F8F8F8;
    }

    input:focus {
        outline: none;
    }
`;

//ListButton
export const Button = styled.div`
    display: flex;
    width: 865px;
    justify-content: flex-end;
    margin-right: 25px;
`;
export const WhiteButton = styled.div`
    width: 90px;
    height: 40px;
    font-size: 16px;
    color: #439F68;
    background-color: white;
    border: 1px solid #439F68;
    border-radius: 10px;
    margin : 15px 15px 0px 0px;
    display: flex;
    align-items: center;
    justify-content: center;

    &:hover {
        cursor: pointer;
    }
`;
export const GreenButton = styled.button`
    width: auto;
    height: 40px;
    font-size: 16px;
    color: white;
    background-color: #439F68;
    border: none;
    border-radius: 10px;
    padding: 0px 20px;
    margin : 15px 0px 0px 0px;
    cursor: pointer;


    a:link{
        text-decoration: none;
        color: #ffffff;
    }
    a:visited{
        font-decoration: none;
        color: #ffffff;
    }

    &:hover {
        font-decoration: none;
        background-color: #5CBE81;
        transition: .25s cubic-bezier(0.43,-0.02, 0.49, 0.95) !important;
    }
`;

//List-More
export const MoreDiv = styled.div`
    display:flex;
    justify-content: center;    
`;
export const GrayButton = styled.button`
    width: 110px;
    height: 35px;
    font-size: 16px;
    color: #767676;
    background: white;
    border: 1px solid #BABABA;
    border-radius: 10px;
    margin : 30px 0px;
    display: flex;
    align-items: center;
    justify-content: center;


    &:hover {
        cursor: pointer;
        background: #F6F6F6;
        transition: .28s cubic-bezier(.4,0,.2,1) !important;
    }
`;


//Footer
export const FooterDiv = styled.div`
    width: 100%;
    height: 150px;
    background-color: #EBEBEB;
    align-items: center;

    p {
        padding: 55px;
        font-size : 12px;
        color: #767676;
    }
`;


export const TestStyle = styled.div`
    color: red;
    border: 1px solid black;
`;

//modal
export const MoreModalDiv = styled.div`
    position: absolute;
    left: 995px;
    top: 66.5%;
    z-index:5;
    border-radius: 5px;
    box-shadow: 2px 2px 5px rgb(190,190,190,0.3) ;
`;

export const StandardModalDiv = styled.div`
    position: absolute;
    right 355px;
    top: 53%;
    z-index:5;
    border-radius: 5px;
    box-shadow: 2px 2px 5px rgb(190,190,190,0.3);
`;